package application;

//import java.awt.Button;
//import java.awt.TextField;
//import java.awt.event.ActionEvent;
//import java.io.IOException;
//import java.sql.SQLException;
//
//import BusinessLogic.Store;
//import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.stage.Stage;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import BusinessLogic.Store;
import PersistenceHandler.dbHandler;
import application.model.Cnt;
import application.model.Search;
import application.model.SearchInWishlist;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class AssignedJob2Controller {
	@FXML
	private Button goback;
	@FXML
	private Button AddtoCart;
	@FXML
	private TextField itemID;
	@FXML
	private TextField Quantity;

	// Event Listener on Button[#goback].onAction
	@FXML
	public void gobackAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AddtoCart].onAction
	@FXML
	public void CartAction(ActionEvent event) throws ClassNotFoundException, SQLException, IOException {
		int id = Integer.parseInt(itemID.getText());
		String time = Quantity.getText();
		 
	       // String address = Address.getText();
	       // dbHandler objdb = new dbHandler();
			//infoBox("Item added sucessfully!!",null,"Successful");
	        //objdb.setPassword(password, tempass, user);
	        Store.getInstance().Assigningjob(id);
	       // Store.getInstance().enterConfirmPassword(tempass);
	    	Parent root = FXMLLoader.load(getClass().getResource("Shopping.fxml")); //need to changee
	    	Stage window = (Stage) AddtoCart.getScene().getWindow();
	    	window.setScene(new Scene(root, 789, 549));
		// TODO Autogenerated
	}
	// Event Listener on TextField[#itemID].onAction
	@FXML
	public void ItemIdAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#Quantity].onAction
	@FXML
	public void QuantityAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
