package application;
//
//import java.awt.Button;
//import java.awt.TextField;
//import java.awt.event.ActionEvent;
//import java.io.IOException;
//import java.net.URL;
//import java.sql.SQLException;
//import java.util.ResourceBundle;
//
//import javax.swing.table.TableColumn;
//import javax.swing.text.TableView;
//
//import BusinessLogic.Store;
//import application.model.delivboysched;
//import javafx.collections.ObservableList;
//import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;
//import javafx.fxml.Initializable;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.stage.Stage;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import BusinessLogic.Store;
import PersistenceHandler.dbHandler;
import application.model.Cnt;
import application.model.Search;
import application.model.SearchInWishlist;
import application.model.delivboysched;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;
public class AssignDeliveryController implements Initializable {
	@FXML
	private Button goback;
	@FXML
	private Button Assignjob;

	// Event Listener on Button[#goback].onAction
	@FXML
	public void gobackAction(ActionEvent event) throws IOException 
	{
		Parent root = FXMLLoader.load(getClass().getResource("AdminHomePage.fxml")); 
    	Stage window = (Stage) goback.getScene().getWindow();
    	window.setScene(new Scene(root, 789, 549));
	}
	@FXML
	public void Assignjob(ActionEvent event) throws IOException {
		
		
		// TODO Autogenerated
	}
	
	
	@FXML
    private TableView<delivboysched> tablee;

    @FXML
    private TableColumn<delivboysched, Integer> id;

    @FXML
    private TableColumn<delivboysched, String> job1;

    @FXML
    private TableColumn<delivboysched, String> job2;

    @FXML
    private TableColumn<delivboysched, String> job3;
    
    private ObservableList<delivboysched> SearchshowItemss; 
    private void loaddata()
	   {
		   id.setCellValueFactory(cellData -> cellData.getValue().getBoy().asObject());
		   job1.setCellValueFactory(cellData -> cellData.getValue().getJob1());
		   job2.setCellValueFactory(cellData -> cellData.getValue().getJob2());
		   job3.setCellValueFactory(cellData -> cellData.getValue().getJob3());

		   
	   }
	    
	    @FXML
	    private void refreshTable() throws SQLException, ClassNotFoundException
	    {
	    	
	    	
	    	
	    }
	    	
	    	public void initialize(URL location, ResourceBundle resources) {
	 

	    	
	    		loaddata();
	    		
	    		

//
	    	}

    @FXML
    private TextField searchTimeField;

    @FXML
    private Button AssignJobButoonn;

    @FXML
    private Button SearchShow;

    @FXML
    void AssignJobButoonnAction(ActionEvent event) throws IOException 
    {
    	Parent root = FXMLLoader.load(getClass().getResource("AssignedJob2.fxml")); 
    	Stage window = (Stage) AssignJobButoonn.getScene().getWindow();
    	window.setScene(new Scene(root, 789, 549));
    }

    @FXML
    void SearchShowAction(ActionEvent event) throws ClassNotFoundException, SQLException 
    {
    	SearchshowItemss = Store.getInstance().SearchDeliveryBoy(searchTimeField.getText());
    	tablee.setItems(SearchshowItemss);
    }

    @FXML
    void searchTimeFieldAction(ActionEvent event)
    {

    }
}
