package application;

import java.awt.Button;
import java.awt.TextField;
import java.awt.event.ActionEvent;

import javax.swing.table.TableColumn;
import javax.swing.text.TableView;

import javafx.fxml.FXML;

public class AssignDeliveryController1 {
	@FXML
	private Button goback;
	@FXML
	private TableView tablee;
	@FXML
	private TableColumn id;
	@FXML
	private TableColumn itemName;
	@FXML
	private TableColumn Material;
	@FXML
	private TableColumn price;
	@FXML
	private TextField SearchItemnameTField;
	@FXML
	private Button RemoveFromWish;
	@FXML
	private Button SearchShow;

	// Event Listener on Button[#goback].onAction
	@FXML
	public void gobackAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#SearchItemnameTField].onAction
	@FXML
	public void SearchItemnameTFieldAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RemoveFromWish].onAction
	@FXML
	public void RemoveFromWishAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#SearchShow].onAction
	@FXML
	public void SearchShowAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
